### PR TITLE
Pi-Yueh Final Project

### PR DESCRIPTION
**Pull request by piyueh**

### CODE REVIEW

**Comment by labarba** [comment]
I dare say, you'll have a chance to do that this semester, when you work with me on the Aerodynamics course :-)

**Comment by mesnardo** [comment]
# On the Kutta Condition in Potential Flow over Airfoil


### 2014


### Authors
* Farzad Mohebbi (Univ. of Canterbury, New Zealand)
* Mathieu Sellier (Univ. of Canterbury, New Zealand)

### Journal
Journal of Aerodynamics

### Citations
`1` (2014/12/31 with Google Scholar)
The citation is another 2014 paper from Mohebbi and Sellier.

### Brief

The authors are solving elliptic PDEs, using a finite-difference method (first order), to both generate the physical grid nodes (from the computational grid nodes) and compute the stream function around different NACA profiles. The elliptic PDEs are solved to a certain tolerance using a fix-point iterative method. All airfoils used in the simulations have a sharp trailing edge, some of them with a finite-angle, the others being cusped. They explicitly derive the Kutta condition for both types of trailing edge. They obtained good agreement (eye-comparison) between the results from this method and results using panel method (taken from the literature).

### Summary

Mohebbi and Sellier present a "novel" and "fast" method to implement the Kutta condition in potential flow over airfoil. Instead of using the classic panel method, they solved elliptic PDEs using a finite-difference method on a O-grid.

The authors are saying that "dealing with the panels and their attributes is numerically more complex than the method proposed in this paper and of high programming effort". Their words...

The grid generation process presented in this paper consists of mapping the irregular physical domain nodes to regular ones in a plane computational domain (map from `(x, y)` to `(xi, eta)`), using elliptic PDEs. To be noted that this technique comes from the the work of Thompson et al. (1967).

Elliptic O-grids have the advantage to be orthogonal to the surface of the airfoil, compared to algebraic O-grids.

The elliptic PDE for the stream function in the computational domain is found by applying the chain rule and using the equations mapping from the physical domain to the computational one. I have done the mathematical derivation and found the same equation.

The authors are also assuming that the control functions in the elliptic PDEs (laplacian of `xi` and laplacian of `eta`) can be set to zero. Unfortunately, they are not saying why they can use this assumption, and there is no reference to previous work using it.

The scheme used to discretize the elliptic PDE is not mentioned.

Definition of the Kutta condition: the flow must leave the sharp trailing edge smoothly.

Then, they are deriving the condition for both the finite-angle trailing edge and the cusped trailing edge.

For a finite-angle, the velocity (tangent to the surface) at the trailing edge has different direction considering the upper side or the lower side. Therefore, the magnitude of the velocity must be zero.

For a cusped trailing edge, the velocity on the upper side the one on the lower side have the same direction. Because the pressure at the trailing edge is unique, it implies that the velocities must be equal (Bernoulli's equation).

Again, the mathematical derivation of the Kutta condition is correct for both types of trailing edge.

Once the stream function is computed to a certain tolerance using a fix-point iterative method, the velocity components, the velocity magnitude as well as the pressure can be calculated at each grid node.

They are also expressing the Kutta condition in terms of the velocity potential, which seems completely irrelevant in this paper.

The authors are computing the surface pressure coefficient of different NACA airfoils, and compare those results with panel method solutions to show the accuracy of their algorithm.

Validation cases:

* finite-angle trailing edge:
  - NACA 0012, AoA=9deg, compared with Anderson's book (Fundamental of Aerodynamics).
  - NACA 0024, AoA=0deg, compared with Houghton and Carpenter (Aerodynamics for engineering students, 2012).
  - NACA 4414, AoA=2deg, compared with XFoil.
  - NACA 4412, AoA=10deg, compared Fearn (Airfoil aerodynamics using panel methods, 2008).

* cupsed trailing edge:
  - NACA 64012, AoA=6deg, compared with XFLR5.

Quote from the paper about the results: "Excellent agreement can be obtained by comparing the results from our method and the ones from the panel method given in validation cases for both finite-angle and the cusped trailing edges."
And that is it for the discussion part.

Instead of all those validation cases (with different NACA airfoils), it would have been nice to see only one finite-angle trailing edge NACA airfoil, using different freestream conditions and a thorough comparison with XFLR5 panel method.

Although they claim to present a fast process, only the run-time from the simulations using their method is given, not the one using other softwares (such as XFLR5). In the end, it is not possible to conclude that their method is faster than panel methods.

About the references:
There are only 10 references, most of them are undergraduate/graduate books. There is a reference the paper presenting the elliptic O-grid generation and references to Drela's work (his 1989 paper explaining the theory behind XFoil and the url where the software XFLR5 can be found).

**Comment by labarba** [comment]
Thanks for the detailed review of the Mohebbi & Sellier paper, @mesnardo. I do not get a very good impression of it. Panel methods are pretty efficient, if you use any form of fast mat-vec, so I think if you are going to make a claim that your method is in any way better, you should compare time-to-solution for the same-accuracy result with the new method and a decent panel method. With open-source codes like XFLR5 available, there's no excuse for not making this comparison.

Besides, this work is only 2D—how complex does their method get in 3D and how will it offer any advantage over panel methods in that case? I'm thoroughly unconvinced of the practical value of their method.

**Comment by mesnardo** [comment]
Hey Pi-Yueh, 

Very nice notebook!

I think the chord-length `c` is missing in your formula for the airfoil half-thickness (beginning of the right hand-side).

Also, it would be great to have a short sentence in each docstring (before listing all the parameters) to explain the purpose of the function.

When plotting with `pyplot`, the semicolon `;` should be on the last instruction, so that IPython only displays the figure (and not the `ylim` for example).

I know that you are using the index `-1` in your formula for convenience (doing in a Python way), but this `-1` is a Python trick (a code trick), and I am kind of reluctant to see it in general mathematical formula (those in markdown cells). But that is just my opinion.

About the iterative loop, you should really avoid using a `while True:` and `break`. The `while` loop should stop when a certain `tolerance` is reached or when a maximum number of iterations is reached, something like:
```python 
while error > tolerance and iteration < max_iterations
```
This way prevents from looping infinitely in the case where the solution does not converge.

Happy New Year!

**Comment by labarba** [comment]
Very good points, @mesnardo!

I particularly agree with the use of the `-1` index trick in formulas. Good catch. This should definitely be modified in the mathematical formulas.

**Comment by labarba** [comment]
@mesnardo, @piyueh : Since we already have a working panel method from the Aero course, could we have a comparison of this finite-difference method and a panel method for the same airfoil, to see how they fare in time-to-solution? The difficulty might be finding two solutions that are equivalent in accuracy, so that the comparison is fair.

**Comment by piyueh** [comment]
Sure! I'll discuss with @mesnardo and try to do that.

**Pull request merged**
